repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml

-   repo: https://github.com/CanadianBoson/helpful-hooks
    rev: v0.0.4
    hooks:
    - id: pretty-json
      args: [ '--autofix', '--no-sort-keys' ]